version: '2'

services:

  orderer.example1-network.com:
    container_name: orderer.example1-network.com
    image: hyperledger/fabric-orderer:1.4.9
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      #- GODEBUG=netdns=go
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/example1-network.com/orderers/orderer.example1-network.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/example1-network.com/orderers/orderer.example1-network.com/tls/:/var/hyperledger/orderer/tls
    - orderer.example1-network.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.abhi.example1-network.com:
    container_name: peer0.abhi.example1-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.abhi.example1-network.com
      - CORE_PEER_ADDRESS=peer0.abhi.example1-network.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.abhi.example1-network.com:7053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.abhi.example1-network.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.abhi.example1-network.com:7051
      - CORE_PEER_LOCALMSPID=abhiMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/abhi.example1-network.com/peers/peer0.abhi.example1-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/abhi.example1-network.com/peers/peer0.abhi.example1-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.abhi.example1-network.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  

  peer0.sava.example1-network.com:
    container_name: peer0.sava.example1-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.sava.example1-network.com
      - CORE_PEER_ADDRESS=peer0.sava.example1-network.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.sava.example1-network.com:9053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sava.example1-network.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.sava.example1-network.com:10051
      - CORE_PEER_LOCALMSPID=savaMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/sava.example1-network.com/peers/peer0.sava.example1-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/sava.example1-network.com/peers/peer0.sava.example1-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.sava.example1-network.com:/var/hyperledger/production
    ports:
      - 9051:9051
      - 9053:9053

  
